development:
  host: localhost
  database: filepile_development

test:
  host: localhost
  database: filepile_test

# set these environment variables on your prod server
production:
  host: 192.168.0.100
  database: filepile

